### ISSUE TITLE
Does an empty string when reading mean connection is lost?

### ISSUE THREAD

**Issue by parhamdoustdar** [clue/php-socket-raw#20]
I am looking for a reliable way to find out whether the connection is still up. What I'm doing is to connect to a remote server with a socket, and enter an infinite loop while constantly calling `$socket->read()`.

What I currently do is to break out of the loop when the length of the string I get from `$socket->read()` is 0. In other words, I quit when the string is `empty`.

Is this the correct strategy? If not, is it possible to add a `$socket->endOfFile()` or something similar? I was expecting `$socket->isAlive()` to help me, but realized that it's doing something else.

Thanks a lot for your great work, and the awesome library!

**Comment by clue** [comment]
> a reliable way to find out whether the connection is still up

This is an interesting question :-)

Unfortunately, this is a bit difficult to answer without knowing your exact use case. This depends on many factors, among your socket protocols / options (TCP/IP?), non-blocking mode, platform, perhaps even your higher level application level protocol and more.

Some random thoughts:

* `man 2 recv` (http://linux.die.net/man/2/recv)
* Socket timeouts
* SO_KEEPALIVE
* Higher-level keepalive messages

Also, this isn't strictly a question this library should answer. This is more of a low-level socket question which applies to the underlying BSD socket library just as well.

If you can rephrase your question to include more details or perhaps a link to a gist, perhaps we can look into giving more details?

I'll close this for now because there's really not much we can do. Feel free to comment back and we can reopen this if it turns out to be an issue here.

**Comment by parhamdoustdar** [comment]
Hi,

Thanks a lot. I stopped working on that project for now so I don't 
remember about this issue, but I will provide more info ASAP.

Thanks!

**Comment by clue** [comment]
Thanks for your patience @parhamdoustdar! Just reply to this ticket once you have more details and we can look into this again.
