### ISSUE TITLE
Socket recv should return the number of bytes read rather than the buffer

### ISSUE THREAD

**Issue by mrrsm** [clue/php-socket-raw#21]
One of the advantages of socket_recv is it returns the length of the data for you.  I believe that method should take the $buffer parameter by ref and return the length as the php function does.

**Comment by mrrsm** [comment]
This would also apply to the function socket_recvfrom

**Comment by clue** [comment]
@mrrsm Thanks for your suggestion and the accompanying PR!

Changing the public interface like this introduces a BC break, so we should consider this thoroughly.
Admittedly, the current implement differs from what the underlying function returns, so this is very well worth discussing!

> One of the advantages of socket_recv is it returns the length of the data for you. I believe that method should take the $buffer parameter by ref and return the length as the php function does.

Personally, I consider the current behavior to be a *convenient feature*. Also, this happens to be in line with how `socket_read()` and `fread()` etc. work. Having used this library is several projects, it also never occurred to me (so far).

Judging from your wording, I'm assuming you have a particular use case in mind which would benefit from this? Perhaps you can elaborate on this use case and how you think the updated API is advantageous? Thanks!

**Comment by mrrsm** [comment]
If you are doing a socket_recv it is taking the liberty of getting my the length of the data it read (which may not be a full read to the length I asked for).   This means that when I get my data back I need to verify that the appropriate amount of data has been received.  

The project I am working on requires us to send a large amount of data around which can end up in partial reads requiring us to validate the return data's length.

This is more of a convenience for me as it reduces a second call I would have to make but this also brings the Socket.php class more inline with the underlying functions, like you said already.

**Comment by mrrsm** [comment]
Also the amount of data we end up sending makes the second call for length add up over time.

I'm porting legacy code and updating it to use classes FYI.

**Comment by clue** [comment]
> validate the return data's length

Sounds like a sane approach either way :-)

> reduces a second call

I'm not sure how relevant this is for PHP for the following reasons:

The underlying socket functions operate on buffers of individual bytes (usually represented as a `char *` in C). Because the buffer may contain any binary data (including NULL bytes) it's impossible to reliably determine the buffer size in C (C's `strlen()` only counts until encountering the first NULL byte, with `O(n)`). Hence, the socket API also returns the buffer size.

However, this doesn't really apply to PHP at all: PHP represents the received buffer as a string which in turn happen to be a data structure which also stores the string length. As such, PHP's strings are binary safe and offer a reliable way to determine its size.

Also, this means that calling PHP's `strlen()` function happens to be `O(1)` (aka. *rather fast*). I'd be surprised if this turns out to be major performance issue in your code.

> inline with the underlying functions […] porting legacy code

I agree that this might be an issue, albeit a smaller one: Porting legacy code requires effort for porting to the OOP API and `Exception` handling anyway, so I'm not sure this is really *that* relevant either.

Personally, I'd rather offer a consistent API surface: `read()`, `recv()`, `recvFrom()` all work very similar – which IMHO is a valid reason to break 1:1 relationship with the underlying socket API.

**Comment by mrrsm** [comment]
>Also, this means that calling PHP's strlen() function happens to be O(1) (aka. rather fast). I'd be surprised if this turns out to be major performance issue in your code.

I agree that it is fast, however it is a call that I shouldn't have to make as that data was already available to me if I used socket_recv which you already have as you checked in

>Personally, I'd rather offer a consistent API surface: read(), recv(), recvFrom() all work very similar – which IMHO is a valid reason to break 1:1 relationship with the underlying socket API.

I can understand wanting to have that common interface between them. It is abstracting away part of the way php decided to implement the function which is what have grown used to using I guess.

Another option, which wouldn't disregard that data, would be to add the length as the data passed by reference rather than the buffer data.
I just feel that I am doing something wrong if I am making another function call to get the length even though we have already got that info and stored it in memory once.

Any thoughts on that?

**Comment by clue** [comment]
> Another option, which wouldn't disregard that data, would be to add the length as the data passed by reference rather than the buffer data.

I agree that this might make this more likely to get in as it does not involve a BC break.

Adding an optional reference parameter for the string length only will result in some added runtime complexity.

If we were talking about some computationally expensive operation (like a cryptographic checksum e.g.), then I'd probably agree that we should indeed add this.

However, for the string length only, I still fail to see the broad applicability of this approach. Checking for the availability of the additional parameter could easily outweigh just invoking `strlen()` if desired.

Would you care to file a (new) PR so we can see how this works out? :+1: 

> I just feel that I am doing something wrong if I am making another function call to get the length even though we have already got that info and stored it in memory once.

I absolute agree that things should be kept in memory: calling `strlen()` essentially just returns a value that is already held in memory :-)

**Comment by clue** [comment]
No further input so far, so I'm closing this via #23.
