### ISSUE TITLE
Disconnect not detected

### ISSUE THREAD

**Issue by danardf** [clue/php-socket-raw#44]
Hi everybody.
I found out a way to detect if a client is disconnected with selecRead(1) and add a try/catch below.
But today it doesn't work anymore.
There's a way to use socket_last_error(), and / or stream_get_meta_data() or something like that?
if I try to use socket_last_error( $Socket->getRessource()), it doesn't work. 

The goal is to detect if the socket (client) is still connected. 
Also, I tried to use write(), with try/catch and it return a error Exception indeed. But I don't would like to send something to detect any disconnect. 

Also I tried to use setBlocking(false) before read() with try/catch and no way. :(

Thank for your help.

**Comment by danardf** [comment]
I found the issue (how to detect)
read(4096, PHP_NORMAL_READ);
Adding this option, now the code detect if the client is disconnected.
I've got an error exception so i can handle it now.

I don't know if this is the best way. 
Why it doesn't work with PHP_BINARY_READ and works with PHP_NORMAL_READ!!!

If somebody could explain me please.?

**Comment by clue** [comment]
Hi @danardf, can you gist the problem you're having?

This project is a very thing wrapper around the sockets extension, so it pretty much exposes how the underlying sockets work.

If the remote end sends a TCP `FIN`, then it will report the connection as "readable" and reading from it should return an empty string. This is expected behavior as also detailed under #20.

If the remote end "dies" without sending a TCP `FIN` (hard power off, sudden network change for mobile devices etc.), then it will not be able to tell you the connection is "dead". It is very common to work around this issue by implementing some higher-level application timeout logic, such as sending a heartbeat message every once in a while.

I hope this helps :+1:
