### ISSUE TITLE
No TLS Support

### ISSUE THREAD

**Issue by sauriio** [clue/php-socket-raw#45]
Hi, there are no way to set the tls connection for the socket object, it assumes that only tcp, icmp and udp are used.

Thank You.

**Comment by cf-git** [comment]
Hello. As I understand it, TLS is a higher level protocol. So you can simply apply additional encryption methods before sending and after receiving of your data. TLS and SSL do same it. Socket it's a method of connection, so it use connection level. Session emulation and cryptography not part of connection protocol. 
May be you can give more information about your task...

Thank you.

**Comment by clue** [comment]
What @cf-git said :) This library is a thin wrapper around PHP's socket APIs (https://www.php.net/manual/en/ref.sockets.php). This low level socket API does not support TLS because TLS is handled by another layer (commonly OpenSSL). Unfortunately, PHP does not provide OpenSSL APIs to create your own TLS stream on top of these low level socket functions.

As an alternative, I would recommend using PHP's stream API (https://php.net/manual/en/book.stream.php) which does support TLS just fine. It operates on a higher level and has built-in support for TLS encryption through OpenSSL :+1:
