### ISSUE TITLE
examples help

### ISSUE THREAD

**Issue by DevWael** [clue/php-socket-raw#53]
Hello,
I'm at the very beginning of using socket.
can you give more examples for this class?

regards.

**Comment by clue** [comment]
@DevWael Welcome to the world of socket programming!

Unfortunately this question is somewhat beyond the scope of this project and I don't see how this could be answered without an in-depth understanding of what you're trying to achieve.

As a first step, I would suggest making yourself familiar with the existing examples, the documentation and/or socket programming in general.

If this is for a commercial project and you're looking for professional support, please check out my profile and send me an email and I'm happy to help. Otherwise, you may want to check out the common community channels (such as IRC, StackOverflow etc.).

I hope this helps and you understand I'm closing this ticket for now. If your problem persists and you feel this is an issue that targets a broader audience, please comment back and we can always re-open this. :+1:
